name: Build Windows Release
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
      - name: Build Windows
        run: flutter build windows --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: jwells-report-windows
          path: build/windows/x64/runner/Release/